#' @title Verify Schema
#'
#' @description This function takes a list generated by importing a YAML file and
#'  verifies if it matches the necessary schema.
#'
#' @param list The list object created by the YAML file.
#'
#' @return Logical
#'
#' @examples
#'  \dontrun{
#'   schm <- yaml::read_yaml("schema.yaml")
#'   verify_schema(schm)
#'  }
#'
#' @author Nathanael Rolim \email{Nathanael.Rolim@@gamail.com}
verify_schema <- function(list){

  # First, verify if the schema file begins with a 'table'
  if(("tables" %in% names(list) == FALSE)){
    rlang::abort("No 'tables' list found in the schema.")
  }

  # Verify if the schema is empty
  if(length(list$tables) == 0){
    rlang::abort("There are no tables defined in 'tables'.")
  }

  # Second, we need to verify if:
  ## (a) Each table is named;
  ## (b) Each table has a rows number;
  ## (c) Each table has at least ONE column
  for(i in 1:length(list)){

    # (a)
    if("name" %in% names(list$tables[[i]]) == FALSE){
      rlang::abort(
        glue::glue("Table {i} is not named.")
      )
    }

    # (b)
    if("rows" %in% names(list$tables[[i]]) == FALSE){
      rlang::abort(
        glue::glue("Table {i} has no number of rows.")
      )
    } else if(typeof(list$tables[[i]]$rows) != "integer"){
      rlang::abort(
        glue::glue("Rows in Table {i} is not a number.")
      )
    }

    # (c)
    if("columns" %in% names(list$tables[[i]]) == FALSE){
      rlang::abort(
        glue::glue("Table {i} has no columns.")
      )
    } else if (typeof(list$tables[[i]]$columns) != "list"){
      rlang::abort(
        glue::glue("Columns in Table {i} is empty.")
      )
    }

  }

  return(TRUE)

}





#' @title Import schema
#'
#' @description This function reads and parses the YAML schema file. It also verifies
#'  if the schema is correct and if all arguments are valid.
#'
#' @param file The YAML schema file
#'
#' @importFrom yaml read_yaml
#'
#' @examples
#'  \dontrun{
#'  importParse("_faker.yaml")
#'  }
#'
#' @author Nathanael Rolim \email{Nathanael.Rolim@@gamail.com}
#'
#' @export
import_schema <- function(file = ""){

  # Read the YAML file
  tables <- yaml::read_yaml(file)

  # Run verify_schema on 'tables' to make sure the schema is correct
  verify_schema(tables)
}


